version: '3'

services:
  nginx:
    build:
      context: docker
      dockerfile: dev/nginx/Dockerfile
    container_name: ${APP_NAME}__nginx
    hostname: ${APP_NAME}__nginx
    volumes:
      - ./:/app
      - ./storage/logs:/var/log/nginx
    ports:
      - ${DOCKER_BRIDGE}:80:80
    restart: always

  php-fpm:
    build:
      context: docker
      dockerfile: dev/php-fpm/Dockerfile
    container_name: ${APP_NAME}__php-fpm
    hostname: ${APP_NAME}__php-fpm
    environment:
      TERM: xterm-256color
      XDEBUG_CONFIG: "client_host=${DOCKER_BRIDGE}"
      PHP_IDE_CONFIG: "serverName=${APP_NAME}"
    volumes:
      - ./:/app
      - ./docker/dev/php/.bashrc:/root/.bashrc

  db:
    image: mysql:5.7
    container_name: ${APP_NAME}__db
    hostname: ${APP_NAME}__db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DOCKER_BRIDGE}:3306:3306
    volumes:
      - ./storage/db/mysql:/var/lib/mysql

  db_testing:
    image: mysql:5.7
    container_name: ${APP_NAME}__db_testing
    ports:
      - ${DOCKER_BRIDGE}:3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jd_db_test
    tmpfs:
      - /var/lib/mysql

  mailer:
    image: mailhog/mailhog
    container_name: ${APP_NAME}__mailer
    hostname: ${APP_NAME}__mailer
    ports:
      - ${DOCKER_BRIDGE}:8025:8025
      - ${DOCKER_BRIDGE}:1025:1025

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK}
