version: "3"

services:

  web:
    image: webdevops/nginx:alpine
    container_name: ${APP_NAME}_web
    hostname: ${APP_NAME}_web
    ports:
      - ${DOCKER_ADDRESS}:80:80
      - ${DOCKER_ADDRESS}:443:443
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_PHP_SOCKET: ${APP_NAME}_php:9000
      LOG_STDOUT: /app/storage/logs/web.access.log
      LOG_STDERR: /app/storage/logs/web.errors.log
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: docker/conf/php/Dockerfile
    container_name: ${APP_NAME}_php
    hostname: ${APP_NAME}_php
    working_dir: /app
    volumes:
      - ./:/app/
      - ./storage/framework/tmp:/tmp
      - ./docker/conf/php/.bashrc:/root/.bashrc
      - ./docker/conf/php/.bash_aliases:/root/.bash_aliases
    environment:
      TERM: xterm-256color
      COMPOSER_ALLOW_SUPERUSER: 1
      XDEBUG_CONFIG: "client_host=${DOCKER_ADDRESS}"
      PHP_IDE_CONFIG: "serverName=${APP_NAME}"
    ports:
      - ${DOCKER_ADDRESS}:6001:6001
      - ${DOCKER_ADDRESS}:8000:8000
    depends_on:
      - db
      - db_testing
      - cache
    entrypoint: ["/bin/bash", "/app/docker/bin/php_start.sh"]

  db:
    image: postgres:14-alpine
    container_name: ${APP_NAME}_db
    ports:
      - ${DOCKER_ADDRESS}:${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/pgsql/:/var/lib/postgresql/data/

  db_testing:
    image: postgres:14-alpine
    container_name: ${APP_NAME}_db_testing
    ports:
      - ${DOCKER_ADDRESS}:5433:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data

  cache:
    image: nbtri/alpine-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: ${APP_NAME}_cache
    hostname: ${APP_NAME}_cache
    ports:
      - ${DOCKER_ADDRESS}:${REDIS_PORT}:${REDIS_PORT}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK}
