version: "3"

services:

  nginx:
    image: webdevops/nginx:alpine
    container_name: ${APP_NAME}_web
    hostname: ${APP_NAME}_web
    ports:
      - ${DOCKER_ADDRESS}:80:80
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public
      WEB_PHP_SOCKET: ${APP_NAME}_php:9000
      LOG_STDOUT: /var/www/html/storage/logs/web.access.log
      LOG_STDERR: /var/www/html/storage/logs/web.errors.log
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php

  php:
    build: ./docker/conf/php/
    container_name: ${APP_NAME}_php
    hostname: ${APP_NAME}_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
      - ./storage/framework/tmp:/tmp
      - ./docker/conf/php/.bashrc:/root/.bashrc
      - ./docker/conf/php/.bash_aliases:/root/.bash_aliases
    environment:
      TERM: xterm-256color
      COMPOSER_ALLOW_SUPERUSER: 1
      XDEBUG_CONFIG: "client_host=${DOCKER_ADDRESS}"
      PHP_IDE_CONFIG: "serverName=${APP_NAME}"
    ports:
      - ${DOCKER_ADDRESS}:6001:6001
    depends_on:
      - pgsql
      - pgsql_testing
      - redis
      - es
    entrypoint: ["/bin/bash", "/var/www/html/docker/bin/php_start.sh"]

  pgsql:
    image: postgres:13.2
    container_name: ${APP_NAME}_pgsql
    hostname: ${APP_NAME}_pgsql
    ports:
      - ${DOCKER_ADDRESS}:${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/pgsql/:/var/lib/postgresql/data/

  pgsql_testing:
    image: postgres:13.2
    container_name: ${APP_NAME}_pgsql_testing
    hostname: ${APP_NAME}_pgsql_testing
    ports:
      - ${DOCKER_ADDRESS}:5433:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data

  pgsql_gps:
    image: postgres:14-alpine
    container_name: ${APP_NAME}_pgsql_gps
    hostname: ${APP_NAME}_pgsql_gps
    ports:
      - ${DOCKER_ADDRESS}:5434:${GPS_DB_PORT}
    environment:
      POSTGRES_DB: ${GPS_DB_DATABASE}
      POSTGRES_USER: ${GPS_DB_USERNAME}
      POSTGRES_PASSWORD: ${GPS_DB_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data

  pgsql_gps_testing:
    image: postgres:14-alpine
    container_name: ${APP_NAME}_pgsql_gps_testing
    hostname: ${APP_NAME}_pgsql_gps_testing
    ports:
      - ${DOCKER_ADDRESS}:5435:${GPS_DB_PORT}
    environment:
      POSTGRES_DB: ${GPS_DB_DATABASE}
      POSTGRES_USER: ${GPS_DB_USERNAME}
      POSTGRES_PASSWORD: ${GPS_DB_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: nbtri/alpine-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: ${APP_NAME}_redis
    hostname: ${APP_NAME}_redis
    ports:
      - ${DOCKER_ADDRESS}:${REDIS_PORT}:${REDIS_PORT}

  es:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    hostname: ${ELASTICSEARCH_HOST}
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - USER=${ELASTICSEARCH_USER}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASS}
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
    restart: on-failure
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}
    networks:
      - default

  mailer:
    image: mailhog/mailhog
    container_name: ${APP_NAME}_mailer
    hostname: ${APP_NAME}_mailer
    ports:
      - ${DOCKER_ADDRESS}:8025:8025
      - ${DOCKER_ADDRESS}:1025:1025

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK}
